--local PL = game:GetService("Players")
--local plr = PL.LocalPlayer
--local btnFolder = plr.PlayerGui:WaitForChild("Interface").Frame


--local Interface = {}

--Interface.MonsterSheet = {
--	ui = plr.PlayerGui:WaitForChild("MonsterSheetUI"),
--	button = btnFolder.MonsterSheet
--}

--function openUI(ui)
--	ui.Enabled = not ui.Enabled
--end

--local monsterSheetBtn = Interface.MonsterSheet.button
--monsterSheetBtn.MouseButton1Click:Connect(function()
--	openUI(Interface.MonsterSheet.ui)
--end)



