-- Updated Data Structure (Template)
return {
	id = nil,
	 
	Level = 1,  	
	
	NewPlayer = true,
	
	Monster = {
		id = nil,
		Name = nil,
		Race = nil, 
		Stage = nil,
		Level = nil,
		Bond = 0, 	
		Wins = 0,
		Age = 0,
		SessionTime = 0, 	
		CareMistakes = 0, 	
		Personality = nil, 	
		Stats = {}, 
		Moves = {},
		History = {},
		Appearance = {},
		BaseRaceFamily = nil, 	
		isNPC = false,
		GeneratedWithLevel = nil,
		Element = nil,
		OwnerId = nil,
	},
	
	
	
	Version = 1.0, }